name: PowerShell Syntax Validation

on:
  push:
    branches:
      - main
    paths:
      - '**.ps1'
      - '**.psm1'
  pull_request:
    branches:
      - main
    paths:
      - '**.ps1'
      - '**.psm1'

jobs:
  validate-powershell:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Validate PowerShell Syntax
        run: pwsh -File ./tests/Test-PowerShellSyntax.ps1
